### ISSUE TITLE
Container dying when I reploy a dokku app

### ISSUE THREAD

**Issue by pmvieira** [nearform/docker-logentries#14]
Hi,

seems that the container exits if i deploy my dokku app.

This is the stack trace that I'm getting on every server:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DestroyableTransform.addListener (events.js:160:15)
    at DestroyableTransform.Readable.on (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:729:33)
    at DestroyableTransform.once (events.js:185:8)
    at DestroyableTransform.Readable.pipe (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:581:8)
    at EventEmitter.attachContainer (/usr/src/app/node_modules/docker-loghose/loghose.js:59:7)
    at EventEmitter.emit (events.js:98:17)
    at /usr/src/app/node_modules/docker-allcontainers/allcontainers.js:52:16
    at /usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/lib/docker.js:192:5
    at Modem.buildPayload (/usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:218:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:179:14)

/usr/src/app/node_modules/docker-loghose/node_modules/never-ending-stream/never-ending-stream.js:14
    stream.destroy()
           ^
TypeError: Cannot call method 'destroy' of null
    at DestroyableTransform.result.destroy (/usr/src/app/node_modules/docker-loghose/node_modules/never-ending-stream/never-ending-stream.js:14:12)
    at detachContainer (/usr/src/app/node_modules/docker-loghose/loghose.js:31:19)
    at EventEmitter.<anonymous> (/usr/src/app/node_modules/docker-loghose/loghose.js:26:5)
    at EventEmitter.emit (events.js:98:17)
    at DestroyableTransform._transform (/usr/src/app/node_modules/docker-allcontainers/allcontainers.js:62:16)
    at DestroyableTransform.Transform._read (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)

```

**Comment by mcollina** [comment]
Are you running the latest build? This should be already fixed (at least the error, the EE memory leak is a new thing)

**Comment by madtechsupport** [comment]
I see the EE memory leak each time I start this container:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at DestroyableTransform.addListener (events.js:160:15)
    at DestroyableTransform.Readable.on (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:729:33)
    at DestroyableTransform.once (events.js:185:8)
    at DestroyableTransform.Readable.pipe (/usr/src/app/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:581:8)
    at EventEmitter.attachContainer (/usr/src/app/node_modules/docker-loghose/loghose.js:59:7)
    at EventEmitter.emit (events.js:117:20)
    at /usr/src/app/node_modules/docker-allcontainers/allcontainers.js:52:16
    at /usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/lib/docker.js:192:5
    at Modem.buildPayload (/usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:221:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-allcontainers/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:182:14)
```

**Comment by mcollina** [comment]
It might be a configuration thing. How many containers are running on that machine?

**Comment by pmvieira** [comment]
@mcollina it might be that, I'll make sure I'm the latest build
 in my case, the EE memory leak happens when I'm running no more than two containers at the same time (the existing one, and the new one I'm deploying side-by-side)

**Comment by mcollina** [comment]
I've just released a new build which should solve these problems. Thanks for your help in addressing these bugs!

**Comment by pmvieira** [comment]
Thanks @mcollina !
I've deployed it in our test servers and so far looks great!

**Comment by mcollina** [comment]
Great to hear!
