### ISSUE TITLE
Running on AWS ECS

### ISSUE THREAD

**Issue by jordi-chacon** [nearform/docker-logentries#22]
Hi!

I am trying to use the LogEntries Docker container within AWS ECS.

My task definition file looks like this:
```json
{
  "containerDefinitions": [
    {
      "name": "my_service",
      "image": "jordichacon/my_service",
      "cpu": 10,
      "memory": 100,
      "essential": true,
      "portMappings": [{"containerPort": 4000,
                        "hostPort": 4000}]
    },
    {
      "name": "logentries",
      "image": "logentries/docker-logentries",
      "cpu": 10,
      "memory": 100,
      "essential": true,
      "command": [
        "-t <token>",
        "-j",
        "-a"
      ],
      "mountPoints": [
        {
          "sourceVolume": "docker_logs",
          "containerPath": "/var/run/docker.sock"
        }
      ]
    }
  ],
  "family": "my_service_task",
  "volumes": [
    {
      "name": "docker_logs",
      "host": {
        "sourcePath": "/var/run/docker.sock"
      }
    }
  ]
}
```

I can see this error when running `docker logs container_id`:
```
/usr/src/app/index.js:124
    arg = arg.split('=');
              ^
TypeError: Object true has no method 'split'
    at /usr/src/app/index.js:124:15
    at Array.reduce (native)
    at cli (/usr/src/app/index.js:123:23)
    at Object.<anonymous> (/usr/src/app/index.js:135:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

What am I doing wrong? Thank you for your help!

**Comment by mikerudolph** [comment]
@jordi-chacon did you fix this error? I am running into it as well, thanks.

**Comment by jordi-chacon** [comment]
@mikerudolph I believe the problem went away when I removed the `-a` flag

**Comment by mikerudolph** [comment]
@jordi-chacon thanks for the reply, I tried removing the `-a` flag but still have the same issue. Will keep digging, thanks.

**Comment by rebyn** [comment]
FYI removing `-a` does it for me.
