### ISSUE TITLE
Container does not start with no stats

### ISSUE THREAD

**Issue by oinopion** [nearform/docker-logentries#23]
Hello, I've deployed `docker-logentries` but it won't start. It crashes with following error:

```
$ docker run logentries/docker-logentries -t private-token-hidden --no-stats
/usr/src/app/index.js:64
  if (!stats && !logs) {
                 ^
ReferenceError: logs is not defined
    at start (/usr/src/app/index.js:64:18)
    at cli (/usr/src/app/index.js:142:3)
    at Object.<anonymous> (/usr/src/app/index.js:148:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Looks like this [line](https://github.com/nearform/docker-logentries/blob/master/index.js#L64) is the problem, and indeed, variable `logs` is not defined anywhere.

**Comment by mcollina** [comment]
Fixed and released, just wait for the automated docker build to complete.
